[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python app_wealth_inequality.py"

